/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SwapIdRouteImport } from './routes/swap.$id'
import { Route as AuthenticatedSwapsRouteImport } from './routes/_authenticated/swaps'
import { Route as AuthenticatedExchangerRouteImport } from './routes/_authenticated/exchanger'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as ApiPublicHooksMonitorDepositsRouteImport } from './routes/api/public/hooks/monitor-deposits'
import { Route as ApiPublicHooksExpireSwapsRouteImport } from './routes/api/public/hooks/expire-swaps'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SwapIdRoute = SwapIdRouteImport.update({
  id: '/swap/$id',
  path: '/swap/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSwapsRoute = AuthenticatedSwapsRouteImport.update({
  id: '/swaps',
  path: '/swaps',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedExchangerRoute = AuthenticatedExchangerRouteImport.update({
  id: '/exchanger',
  path: '/exchanger',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicHooksMonitorDepositsRoute =
  ApiPublicHooksMonitorDepositsRouteImport.update({
    id: '/api/public/hooks/monitor-deposits',
    path: '/api/public/hooks/monitor-deposits',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksExpireSwapsRoute =
  ApiPublicHooksExpireSwapsRouteImport.update({
    id: '/api/public/hooks/expire-swaps',
    path: '/api/public/hooks/expire-swaps',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/account': typeof AuthenticatedAccountRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/exchanger': typeof AuthenticatedExchangerRoute
  '/swaps': typeof AuthenticatedSwapsRoute
  '/swap/$id': typeof SwapIdRoute
  '/api/public/hooks/expire-swaps': typeof ApiPublicHooksExpireSwapsRoute
  '/api/public/hooks/monitor-deposits': typeof ApiPublicHooksMonitorDepositsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/account': typeof AuthenticatedAccountRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/exchanger': typeof AuthenticatedExchangerRoute
  '/swaps': typeof AuthenticatedSwapsRoute
  '/swap/$id': typeof SwapIdRoute
  '/api/public/hooks/expire-swaps': typeof ApiPublicHooksExpireSwapsRoute
  '/api/public/hooks/monitor-deposits': typeof ApiPublicHooksMonitorDepositsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/exchanger': typeof AuthenticatedExchangerRoute
  '/_authenticated/swaps': typeof AuthenticatedSwapsRoute
  '/swap/$id': typeof SwapIdRoute
  '/api/public/hooks/expire-swaps': typeof ApiPublicHooksExpireSwapsRoute
  '/api/public/hooks/monitor-deposits': typeof ApiPublicHooksMonitorDepositsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/faq'
    | '/how-it-works'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/account'
    | '/admin'
    | '/exchanger'
    | '/swaps'
    | '/swap/$id'
    | '/api/public/hooks/expire-swaps'
    | '/api/public/hooks/monitor-deposits'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/faq'
    | '/how-it-works'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/account'
    | '/admin'
    | '/exchanger'
    | '/swaps'
    | '/swap/$id'
    | '/api/public/hooks/expire-swaps'
    | '/api/public/hooks/monitor-deposits'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/faq'
    | '/how-it-works'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/_authenticated/account'
    | '/_authenticated/admin'
    | '/_authenticated/exchanger'
    | '/_authenticated/swaps'
    | '/swap/$id'
    | '/api/public/hooks/expire-swaps'
    | '/api/public/hooks/monitor-deposits'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  FaqRoute: typeof FaqRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  SwapIdRoute: typeof SwapIdRoute
  ApiPublicHooksExpireSwapsRoute: typeof ApiPublicHooksExpireSwapsRoute
  ApiPublicHooksMonitorDepositsRoute: typeof ApiPublicHooksMonitorDepositsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/swap/$id': {
      id: '/swap/$id'
      path: '/swap/$id'
      fullPath: '/swap/$id'
      preLoaderRoute: typeof SwapIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/swaps': {
      id: '/_authenticated/swaps'
      path: '/swaps'
      fullPath: '/swaps'
      preLoaderRoute: typeof AuthenticatedSwapsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/exchanger': {
      id: '/_authenticated/exchanger'
      path: '/exchanger'
      fullPath: '/exchanger'
      preLoaderRoute: typeof AuthenticatedExchangerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/hooks/monitor-deposits': {
      id: '/api/public/hooks/monitor-deposits'
      path: '/api/public/hooks/monitor-deposits'
      fullPath: '/api/public/hooks/monitor-deposits'
      preLoaderRoute: typeof ApiPublicHooksMonitorDepositsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/expire-swaps': {
      id: '/api/public/hooks/expire-swaps'
      path: '/api/public/hooks/expire-swaps'
      fullPath: '/api/public/hooks/expire-swaps'
      preLoaderRoute: typeof ApiPublicHooksExpireSwapsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedExchangerRoute: typeof AuthenticatedExchangerRoute
  AuthenticatedSwapsRoute: typeof AuthenticatedSwapsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedExchangerRoute: AuthenticatedExchangerRoute,
  AuthenticatedSwapsRoute: AuthenticatedSwapsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  FaqRoute: FaqRoute,
  HowItWorksRoute: HowItWorksRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  SwapIdRoute: SwapIdRoute,
  ApiPublicHooksExpireSwapsRoute: ApiPublicHooksExpireSwapsRoute,
  ApiPublicHooksMonitorDepositsRoute: ApiPublicHooksMonitorDepositsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
